### ISSUE TITLE
Bindings for Instance Group Managers?

### ISSUE THREAD

**Issue by toots** [googleapis/nodejs-compute#103]
Hi,

Any reason the instance group manager API calls aren't covered yet? Y'all taking PR for that?

**Comment by stephenplusplus** [comment]
Sure, a PR would be great!

**Comment by toots** [comment]
Feel free to go ahead. I'm slammed right now and won't have time to look at it for a while.

**Comment by sofisl** [comment]
Hi, please refer to the new library, ^3.0.0.
