### ISSUE TITLE
Bug: Attaching existing disk when creating a new VM

### ISSUE THREAD

**Issue by thoughtspeed7** [googleapis/nodejs-compute#107]
This is probably a bug. I am trying to create a new VM by attaching an existing disk to it. But I get the `Invalid value for field 'resource.disks[0].source': ''. Source url of disk is missing.` error when running below code. Get the same error when I pass disk.get() results to the zone.createVM() method if at all that helps. Can someone help? I have a deadline to meet on this piece of functionality. You can also check https://stackoverflow.com/questions/50968528/create-a-new-vm-by-attaching-an-existing-disk-using-node-js-client-library-for-g for discussions on this so far. Thanks in advance!

    const main = (req, res) => {

        const Compute = require('@google-cloud/compute');
        const compute = new Compute();
        const zone = compute.zone('us-central1-f');
        let disk;
        const diskName = 'debian-http';
        const vmName = 'debian-http'
        let vm;

        disk = zone.disk(diskName);
        
        zone.createVM(vmName, {
            disks: [disk], 
            http: true, 
            machineType: 'f1-micro'
        })
        .then((data) => {
            vm = data[0];
            const operation = data[1];
            return operation.promise();
        })
        .then(() => {
            console.log('vm created successfully');   
            res.send('vm created successfully');     
        })
        .catch((e) => {
            console.error(e);
            res.send(e.message);
        });    

    };

**Comment by thoughtspeed7** [comment]
Thanks for your input. I've tried passing the expected JSON directly but get the same error. Also, I don't see any property by the name "source" on the Disk resource documentation which is what is expected by the REST API as per the error I get. Can you help me with how to get a reference to an existing disk and pass it to the zone.createVM method? There is no documentation for this. Thanks.

**Comment by stephenplusplus** [comment]
Sorry for my mistake, it looks like our docs aren't correct. We don't expect a `Disk` resource as the API describes, but an object formatted according to the specifications under `disks` here: https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

We will update our docs to point there instead.

**Comment by theacodes** [comment]
This has show up again https://stackoverflow.com/questions/50968528/create-a-new-vm-by-attaching-an-existing-disk-using-node-js-client-library-for-g

**Comment by thoughtspeed7** [comment]
Yes, the documentation at https://cloud.google.com/nodejs/docs/reference/compute/0.10.x/Zone#createVM is incorrect. I made this work by passing raw JSON to the zone.createVM method as below:

    zone.createVM('debian-http', {
        disks: [{
            boot: true,
            source: 'https://www.googleapis.com/compute/v1/projects/[project-id]/zones/us-central1-f/disks/debian-http'
        }], 
        http: true, 
        machineType: 'f1-micro'
    })

More config options for the disks property can be found at https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert. Hope this helps others!
