### ISSUE TITLE
Service Account and Access Scopes

### ISSUE THREAD

**Issue by thoughtspeed7** [googleapis/nodejs-compute#111]
Pardon me if I am wrong but I have gone through the documentation and can't figure out a way to specify the Service Account and Access Scopes to use while creating a new VM. If this is not possible currently:

1) Can this be considered as a feature request?
2) What's the best way to achieve this until this feature request is implemented.

If I am wrong and this is possible, can you shed some light on how to implement this.

Thanks.

**Comment by stephenplusplus** [comment]
I believe you just pass it in to our `zone.createVM` method:

```js
zone.createVM('name', {
  serviceAccounts: [
    {
      email: '...',
      scopes: [
        '...'
      ]
    }
  ]
})
```

API reference: https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

Let me know if you have any issues with this.

**Comment by thoughtspeed7** [comment]
Works. Thanks for your fantastic and timely support on this. Does that mean I can pass other raw JSON snippets to the zone.createVM method for use cases not covered natively by the client library yet?

**Comment by stephenplusplus** [comment]
Yep, the transparency is meant to be a feature / philosophy of the library. We special-case common scenarios, but try to maintain 1:1 compatibility with the upstream API. That means we shouldn't block any raw input, in this method or others. But, if you do find places where we're shutting out raw API options, please let us know!
