### ISSUE TITLE
setLabels method feature request

### ISSUE THREAD

**Issue by jkwlui** [googleapis/nodejs-compute#116]
*From customer:*

We use cloud function to label all of the instances created in our projects with the user id of the person who created it. This way we can notify the user when their instance comes under governance. Basically we create a sink from the gce instance log and filter it to look at insert events. This gets written to a bucket (or a pub/sub topic) that triggers a cloud function to run.
 

Here is what our instance tagging cloud function looks like.

 

exports.processFile = function(event, callback) {

    // Requires

    const path = require('path');

    const os = require('os');

    const fs = require('fs');

    const readline = require('readline');

    var storage = require('@google-cloud/storage')();

    var google = require('googleapis');

    var compute = google.compute('beta');

 

That obviously changed since the compute is now v1. But if I try either I get the following error.

2018-05-14 08:18:08.522 EDTnetapp-hcl-func 101128355950845 TypeError: google.compute is not a function at exports.processFile (/user_code/index.js:19:27) at 

 

So I try this one that gives me almost everything I need.

const Compute = require('@google-cloud/compute');

const compute = new Compute();

 

Except there is no setLabels() API anywhere to be found in that Node.js package.

**Comment by coral194** [comment]
is there an update?
