### ISSUE TITLE
Not possible to use `container-vm`

### ISSUE THREAD

**Issue by akoenig** [googleapis/nodejs-compute#122]
#### Environment details

  - OS: `macOS (10.13.5)`
  - Node.js version: `8.11.3`
  - npm version: `5.6.0`
  - `@google-cloud/compute` version: `0.10.0`

#### Steps to reproduce

  1. Create a new compute instance by defining `container-vm` as `os`

```js
const config = {
  os: "container-vm",
  http: true
};
```

#### Result

The error `Could not find a suitable image.` will be thrown. I just tinkered a little bit with the naming and tried `cos-stable` as well, but in this case the library throws `Expected one of: centos, container-vm, coreos, debian, redhat, opensuse, suse, ubuntu, windows` which is the correct behaviour. Anyways, using the suggested `container-vm` leads to the error above.

**Comment by stephenplusplus** [comment]
I just [published a fix](https://github.com/stephenplusplus/gce-images/pull/9) on the library that manages those URLs. Please un- and re-install `@google-cloud/compute`, and let me know if there are any problems.

**Comment by akoenig** [comment]
Awesome, thanks for the fast response and the fix 👍
