### ISSUE TITLE
Allow update of the firewall rule for non-default network.

### ISSUE THREAD

**Issue by apankratov** [googleapis/nodejs-compute#125]
#### Description

When updating firewall rule `network` metadata field is ignored and replaced with `global/networks/default`.

Here `Compute` object metadata `network` field is set to default:
https://github.com/googleapis/nodejs-compute/blob/master/src/firewall.js#L190

Here when  `setMetadata` method is called `network` field from argument is ignored and overridden by default one:
https://github.com/googleapis/nodejs-compute/blob/master/src/firewall.js#L284

#### Proposal

Set metadata argument `network` field to default only if not specified explicitly by the caller.

#### Environment details

  - OS: Google Cloud Platform
  - Node.js version: default
  - npm version: default
  - `@google-cloud/compute` version: 0.10.0

#### Steps to reproduce

1) Assuming non-default network name is `infra-common-vpc`

2) Create cloud function with sample code:
```
 // Imports
const Compute = require('@google-cloud/compute');

// Google Cloud API configuration
const GCFirewallRuleName = 'test-fw-rule'
const compute = new Compute();
const firewall = compute.firewall(GCFirewallRuleName);

exports.fw_test = (CFreq, CFres) => {
    updateFirewallRule(["8.8.8.8", "4.4.4.4"], CFres);
};

function updateFirewallRule(ingressIPs, CFres) {
  // Add the mask /32 to each IP
  ingressIPs = ingressIPs.map(function(e) {return e + '/32'});

  // Set the fields we want to update in the firewall rule
  const metadata = {
    sourceRanges: ingressIPs,
    network: "global/networks/infra-common-vpc",
    description: "Allow ingress"
  };

  // Update the firewall rule
  firewall.setMetadata(metadata, function(err, operation, apiResponse) {
    if (err) {
      CFres.status(500).send(apiResponse).end();
    } else {
      CFres.status(200).end();
    }
  });
}
```

3) Create firewall rule for non-default network. E.g. using `gcloud`:
`gcloud compute firewall-rules create test-fw-rule --network infra-common-vpc --allow tcp`

4) Run the function and check that firewall rule is updated, but network is changed to `default` and thus the scope it applies to is changed.

**Comment by stephenplusplus** [comment]
This makes sense to me. Would you be interested in sending a PR? It would look something like:

```js
metadata = extend({
  name: this.name,
  network: this.metadata.network,
}, metadata);
```
