### ISSUE TITLE
Provide key json into constructor as string

### ISSUE THREAD

**Issue by nodesocket** [googleapis/nodejs-compute#209]
Is it possible using the constructor

```js
const gce = new Compute({
    keyFilename: './my-project.json'
});
```

Instead of providing a path on disk for `keyFilename`, to provide a string that is the key json? The reason I ask is that we don't want to write the key json to disk as we store it securely in [HashiCorp Vault](https://www.vaultproject.io).

**Comment by stephenplusplus** [comment]
I think this should work:

```js
const gce = new Compute({
  credentials: JSON.parse(getStringFromVault())
})
```

Let me know if that's not working!

**Comment by nodesocket** [comment]
@stephenplusplus, having issues with the newline characters in the private key:

```javascript
// credentials is string containing the json key
const gce = new Compute({
    credentials: JSON.parse(credentials.replace(/\n/g, '\\n'))
});
```

I am trying to just escape `\n` with `\\n`, but this is breaking the `JSON.parse()`.

```
SyntaxError: Unexpected token \ in JSON at position 1
```
