### ISSUE TITLE
License does not specify copyright correctly

### ISSUE THREAD

**Issue by rageshkrishna** [googleapis/nodejs-compute#253]
Your [license](https://github.com/googleapis/nodejs-compute/blob/ee962dd9d1b5b068d5db6a7745cc0d722ac28ba4/LICENSE#L190) still says `Copyright [yyyy] [name of copyright owner]`. I think this needs to be updated.

**Comment by JustinBeckwith** [comment]
Oh gosh darn it.  @stephenplusplus could you update the template in synthtool, and send out a hammer PR?

**Comment by stephenplusplus** [comment]
That's actually how it's supposed to be! I was confused at first too ([proof](https://github.com/googleapis/nodejs-storage/pull/49/files)) but the preceding paragraph explains it.

**Comment by JustinBeckwith** [comment]
Sweet, so I didn't screw up! 🤣  Thank you for your superior critical reading skills @stephenplusplus.

**Comment by rageshkrishna** [comment]
@stephenplusplus Thanks for clearing this up. So this is just the raw license, and this template gets filled out in the actual source. I learned something new today. Thank you!
