### ISSUE TITLE
Possibility to set labels on a VM/instance

### ISSUE THREAD

**Issue by unludo** [googleapis/nodejs-compute#256]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**

 **Describe alternatives you've considered**
Using the nodejs generic google api

 **Additional context**

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the issue!  We're tracking this over in #116, so please follow that issue for updates.
