### ISSUE TITLE
VM is not available for ssh connection on operation complete

### ISSUE THREAD

**Issue by sorsaffari** [googleapis/nodejs-compute#336]
#### Environment details

  - OS: `Mac 10.14.5`
  - Node.js version: `12.6.0`
  - npm version: `6.9.0`
  - `@google-cloud/compute` version: `1.1.1`

#### Steps to reproduce

  1. create a VM using the compute client
  2. on operation `complete`, spawn a `bash` child process to ssh into the created vm using the `gcloud compute ssh` command.
  3. process fails with `ssh: connect to host <external-ip> port 22: Connection refused`

However if the `gcloud` command is run _not immidiately_ after `operation.on('complete', ...)` is triggered, but rather with a slight delay, the ssh connection is made successfully.

**Comment by stephenplusplus** [comment]
The operation that is returned from an "instances.create" operation is an "insert" operation. When that operation finishes, the state can be any of the ones listed here: https://cloud.google.com/compute/docs/instances/instance-life-cycle.

To wait for the `RUNNING` event, we actually have a method called "vm.waitFor()"! https://googleapis.dev/nodejs/compute/latest/VM.html#waitFor

Let me know if there are any issues with this solution.

**Comment by sorsaffari** [comment]
Thank you @stephenplusplus for your reply.

As stated in the life cycle documentation:
> `RUNNING` - The instance is booting up or running. You can connect to the instance _shortly_ after it enters this state. 

Seems to me there is no state that guarantees the instance has been booted up fully and is available for ssh connection. I've tried `vm.waitFor('RUNNING')` and `operation.on('complete')` and they both seem to have the same issue as described in the original post.

**Comment by JustinBeckwith** [comment]
If it's at all any help - we have an example of polling / retrying a connection after bootup here:
https://github.com/googleapis/nodejs-compute/blob/master/samples/startupScript.js

This could probably be adapted to attempt creating a network connection to 22, just to know when the socket is accepting connections.

**Comment by sorsaffari** [comment]
That's helpful, thank you @JustinBeckwith :)
