### ISSUE TITLE
Region.instanceGroup

### ISSUE THREAD

**Issue by bytechase** [googleapis/nodejs-compute#352]
As of now, it does not look like there is any possible way to retrieve an instance group that is on a region and not a zone.

For instance when the instance group is on a zone you can simply use 
zone.instanceGroup

There is no region.instanceGroup property.

**Comment by stephenplusplus** [comment]
True! Interested in sending a PR by any chance?

**Comment by bytechase** [comment]
PR?

**Comment by stephenplusplus** [comment]
Sorry, a pull request to our repository here to add the feature. No pressure, just checking :)

**Comment by bytechase** [comment]
No problem Stephen

**Comment by WestonThayer** [comment]
@stephenplusplus I took a look at making a PR here, but had some questions. Right now the InstanceGroupManager object is [constructed with a zone](https://googleapis.dev/nodejs/compute/latest/InstanceGroupManager.html) that's used as the `baseUri` for any future API calls. Obviously that throws a wrench in the [regionInstanceGroupManagers API](https://cloud.google.com/compute/docs/reference/rest/v1/regionInstanceGroupManagers/list), which expects `region` to be at the `baseUri`.

Is the right fix to create a new RegionInstanceGroupManager class and extract any common functionality to some shared base class? Or should InstanceGroupManager be made flexible so it can be single-zone or regional? The former option is a bit closer to the underlying REST APIs, but it's a bit more verbose.

Similarly, should the Compute object get a `getRegionInstanceManagers` method?

**Comment by stephenplusplus** [comment]
Hey @WestonThayer, thank you for taking the time to help us with this. I think we can support both `instanceGroupManagers` and `regionInstanceGroupManagers` REST APIs with the same InstanceGroupManager class. We should just need to expose a new method, `instanceGroupManager()` from the Region class to match what's in the Zone class: https://github.com/googleapis/nodejs-compute/blob/227f43fc957b2592a43477914981c0da201b4128/src/zone.js#L1315-L1332. The base URL is constructed by taking into account the `parent` argument, which would now be a `Region` instance-- that *should* give us the correct URL.

> Similarly, should the Compute object get a getRegionInstanceManagers method?

Yes, that would be great 👍

**Comment by WestonThayer** [comment]
Thanks for the guidance @stephenplusplus. Unfortunately, I don't think I have reason to make these changes anymore. I'm moving towards the raw `googleapis` library for a few reasons:

- Typescript support
- Access to alpha and beta APIs (for me, the new suspend/resume feature on instances is really important)
- I'm generally concerned about this library being at risk for lagging behind the current Google APIs

I might swing back around if I had more insight into these, but that's where I'm at right now.
