### ISSUE TITLE
Adding "urlMaps" API

### ISSUE THREAD

**Issue by K4ST0R** [googleapis/nodejs-compute#355]
I want to use the **urlMaps** API to be able to invalidateCache from Nodejs.
Is there a plan to add it to the **nodejs-compute** API ?
If not, I will be happy to contribute.

Reference :
https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps?authuser=1#resource-urlmap

**Comment by callmehiphop** [comment]
👋 @K4ST0R I don't think this is on anyone's radar, but we're always happy to accept pull requests!
