### ISSUE TITLE
Invalid value for field 'region': 'asia-northeast3'. Unknown region."

### ISSUE THREAD

**Issue by lukasschwab** [googleapis/nodejs-compute#390]
#### Environment details

  - OS: Mac OS 10.14
  - Node.js version: v13.3.0
  - npm version: 6.13.2
  - `@google-cloud/compute` version: 1.1.8

#### Steps to reproduce

``` javascript
const compute = new Compute({
  credentials,
  projectId
});
const [networks] = await compute.getNetworks();
const network = networks[0];
const [subnets] = await network.getSubnetworks();

await Promise.all(subnets.map(subnet => subnet.getMetadata()))
```

This yields a 400 error with the message `Invalid value for field 'region': 'asia-northeast3'. Unknown region.`.

Indeed, `gcloud compute regions list` does not list `asia-northeast3`, and it is not listed in the [regions documentation](https://cloud.google.com/compute/docs/regions-zones/). 

`asia-northeast3` *is* listed in the Console:

<img width="372" alt="Screen Shot 2020-01-17 at 11 38 37" src="https://user-images.githubusercontent.com/4955943/72641025-fb3af000-391d-11ea-838b-096680414c4c.png">

**Comment by lukasschwab** [comment]
Perhaps this should be filed with the Compute team rather than with the client library; happy to re-file/redundantly file it.

**Comment by JustinBeckwith** [comment]
Greetings!  I would be surprised if this was specific to the library, as you mentioned.  One thing that makes it easier to pin down - can you reproduce the issue using the API explorer?
https://cloud.google.com/compute/docs/reference/rest/v1/

If you can reproduce the problem there, it makes things clear the underlying API is the culprit.  With a basic test, I was unable to reproduce this sadly. 

If it does turn out to be a Compute Engine problem - you want to start with support if you have a support contract, or otherwise file an issue here:
https://issuetracker.google.com/savedsearches/559755

Hope this helps!  Let us know how things go :)

**Comment by lukasschwab** [comment]
I was unable to reproduce the error in the API explorer this morning; I reverted my work-around, and the error is no longer occurring in my project either.

Seems that this was a blip in the underlying API:

+ https://github.com/tektoncd/plumbing/issues/186
    + Mentions: "It looks like the consensus is that gcloud itself had an outage (i.e. the API it communicates with)."
+ https://github.com/kubernetes/test-infra/pull/15951

Using the API explorer to distinguish between client and API errors is clever––I'll use it in the future.

Thanks for the reply!

**Comment by hermes2014** [comment]
This issue doesn't seem to be the problem with the Node.js API. The same error occurs when trying to create an instance in the Seoul region in the GCP web interface.
"요청에 잘못된 인수가 포함됨: 'Invalid value for field 'zone': 'asia-northeast3-a'. Unknown zone..' 오류 코드: 'invalid' "
It seems that the GCP Seoul Region is not fully ready yet. I have to wait a little longer.

**Comment by rudebono** [comment]
me too,
still error occur

**Comment by yhware** [comment]
@lukasschwab Hey do you mind opening the issue up again? I'm facing the same issue even with the latest sdk with the following error.

ERROR: (gcloud.compute.networks.subnets.create) Could not fetch resource:
 - Invalid value for field 'region': 'asia-northeast3'. Unknown region.

**Comment by JustinBeckwith** [comment]
Greetings!  This is mostly not an issue with the npm module, and rather a problem with the API.  Please see https://github.com/googleapis/nodejs-compute/issues/390#issuecomment-577019099

**Comment by gneyal** [comment]
I'm also getting Invalid value for region: us-east1-c
