### ISSUE TITLE
question: how does nodejs-compute know what is the gcloud configured default project?

### ISSUE THREAD

**Issue by chapmanjacobd** [googleapis/nodejs-compute#396]
what is the equivalent to `gcloud config get-value project` for nodejs-compute? (or is it inaccessible?)

my use case is that I want to know what to write for the second part of this:

```
const PROJECT_NAME = process.env.GCLOUD_PROJECT || `gcloud config get-value project` ;
```

somehow nodejs-compute knows when GCLOUD_PROJECT isn't set, but I don't know how it knows, ya know?

**Comment by chapmanjacobd** [comment]
There is compute.getProjectId but it returns a pending object

**Comment by bcoe** [comment]
@chapmanjacobd you should be able to do this:

```js
async main () {
  const project = await compute.getProjectId()
}
main()
```

:+1: let me know if this does the trick for you?

**Comment by chapmanjacobd** [comment]
thank you 

 `async main () {` 
:national_park: :scroll: :evergreen_tree: :leaves: :bow_and_arrow: :boar: :fire: :meat_on_bone: :yum: :walking_woman: :eyes: :evergreen_tree: :camping: :meat_on_bone: :baby: 
`}`
