### ISSUE TITLE
No indication that quota exceeded  when returning from zone.createVM

### ISSUE THREAD

**Issue by ryan65** [googleapis/nodejs-compute#459]
OS: Ubuntu / windows
Node.js version: 12.13.1
npm version: 6.12.1
@google-cloud/compute version: 2.0.1

Steps to reproduce:
run more than 4 c2-standard-8 in region with quota 24.

createVM returns that everything is OK for all 4 machines. no error , nothing.
but after a while one of the machines are deleted. and when calling vm.getMetadata we receive an error
the resource 'projects/myproj/zones/us-east4-c/instances/cdiabhhfchhjjeef1c-1593608453876' was not found",

Expected:
createVM should return an error if the quota is exceeded.
this is basic behaviour since the machine will not be launched successfully so createVM MUST return an error.
 how can I know that the quota was exceeded otherwise.
THIS IS CRITICAL behaviour for our system. especially considering some of the machine quotas are small and we sometimes launch many machines. 
We must know the reason for failure , so that if its a quota issue, we can send a request to increase the quota.

**Comment by ryan65** [comment]
Hi
is there any estimate when this will be fixed?
we need this fix quite urgently.
Thanks.

**Comment by bcoe** [comment]
@ryan65, I brought this issue up with @stephenplusplus (who has some familiarity with this library), he asks:

> could you provide an example of code that shows how you're invoking `createVM`.

As much context as you could provide the better.

**Comment by ryan65** [comment]
Hi  stephen.
Thanks for the response.
We just got to understand from google support, that if we call operation.promise() directly after the createVM call then we do get the QUOTA_EXEEDED error. 
The question is , is this the way it should be, ?
I think createVM should return this error directly ,just like it returns other errors, like bad image or zone.
this is how other all other cloud provider apis work. using the promise() call is quite confusing and not intuitive.
In GCP , the behaviour is strange when the quota is exceeded.
a machine is launched and then immediately deleted. this is confusing , 

anyway this code below works for us , so the issue is less urgent for now since we can use operation.promise().

      const [vm, operation] = await zone.createVM(vmName, config);
      await operation.promise();
        ....

**Comment by stephenplusplus** [comment]
Thanks @ryan65. 

> In GCP , the behaviour is strange when the quota is exceeded. a machine is launched and then immediately deleted. this is confusing ,

Just to separate the issues, this is one that we can't address from this library. That's upstream behavior that we have to work with from this layer.

> if we call operation.promise() directly after the createVM call then we do get the QUOTA_EXEEDED error. The question is , is this the way it should be, ?

I understand this viewpoint, and this could be a place where there's not a correct answer that will suit everyone. Some would appreciate having the option of being able to have their script move on after sending the "createVM" call without delay, and managing the operation later (if at all).

I think offering the flexibility is best, and is consistent with the other parts of this library as well as our other libraries which use API's that require a delay before knowing the result of the operation.

Within your codebase, you could try a helper function like:

```js
const Compute = require('@google-cloud/compute');

async function onOperationComplete(promise) {
  try {
    const [...args] = await promise;
    for (const arg in args) {
      if (arg instanceof Compute.Operation) {
        await operation.promise();
        break;
      }
    }
    return args;
  } catch (e) {
    throw e;
  }
}
```

Then call it wherever you use an API method that returns an Operation:

```js
try {
  const [vm] = await onComplete(zone.createVM(vmName, config));
} catch (e) {
  // Error
}
```

Hopefully this is a useful option that will not cause too much pain!
