### ISSUE TITLE
Compute module constructor adds apiEndpoint attribute to the given configuration

### ISSUE THREAD

**Issue by lbaldini** [googleapis/nodejs-compute#460]
I've been using version 0.8.0 of @google-cloud/compute for a long time. A couple of months ago I've decided to move to what was the latest at the moment: version 1.2.0.
I'm using also @google-cloud/storage and I've updated that as well (from 1.5.0 to 4.7.0).

My app started to have random problems getting a 404 when I tryied to access private resources. After restarting my app it was working for some time then, after running smoothly for days, it was having problems.

I 've identified the problem in this call:

```
var gce = new (require("@google-cloud/compute"))(MyConf);
```

This call changes the given configuration by adding a new attribute:
`{ apiEndpoint: 'compute.googleapis.com' }`

The MyConf object is created as at the beginning of my app and it's used for both calls: compute and storage. 
The compute call adds the attribute that gives problem when I use that same configuration as parameter for the storage module.

- OS: Linux alpine inside Docker
- Node.js version: 12.18.0
- npm version: 6.14.4
- `@google-cloud/compute` version: 1.2.0

I've solved my problem by cloning the MyConf object before calling the compute module's contructor but I think that it would be better if the compute library did't change the configuration as the storage module does.

**Comment by lbaldini** [comment]
I've checked with version 2.0.1 (the latest available now) and it still adds the attribute.

**Comment by stephenplusplus** [comment]
Sorry about that and thanks for writing this up. PR incoming.

**Comment by lbaldini** [comment]
> Sorry about that and thanks for writing this up. PR incoming.

No problem at all!!! Thankx! :-))))
