### ISSUE TITLE
update a VM's deletion protection flag

### ISSUE THREAD

**Issue by memyselfandm** [googleapis/nodejs-compute#477]
**Is your feature request related to a problem? Please describe.**
This client can only set the `deletionProtection` flag on a VM on `vm.create()`.
I need to be able to update this value for VMs at some point after the VM is created, usually in order to delete it.
 **Describe the solution you'd like**
Something like `vm.setDeletionProtection()`
 **Describe alternatives you've considered**
I've tried using `vm.setMetadata({"deletionProtection":false})` but the flag can't be changed in this way.
 **Additional context**
I'm writing a cloud function to help with VM cleanup.

**Comment by stephenplusplus** [comment]
Thanks for reporting. It looks like our "setMetadata" method isn't consistent with what you'd expect from our other APIs. Usually, "setMetadata()" will update the record of the resource, so you'd expect `vm.setMetadata({"deletionProtection":false})` to do just that. In this case, the "Metadata" of "set*Metadata*" means the actual concept of "metadata" as the API designed: https://cloud.google.com/compute/docs/reference/rest/v1/instances/setMetadata

So, I think we should add a new method "update", which would behave as you would normally expect "setMetadata" to. In this case, "vm.update({"deletionProtection":false})" would work as intended.

**Comment by stephenplusplus** [comment]
PR sent #478. Please take a look and share any thoughts or ideas. Thanks!

**Comment by stephenplusplus** [comment]
2.1.0 is out with the new `update()` method 🥳
