### ISSUE TITLE
vm.update() can't update deletionProtection flag. 

### ISSUE THREAD

**Issue by memyselfandm** [googleapis/nodejs-compute#484]
This essentially re-opens #477 .

The new feature adding `vm.update()` in #478 was implemented in part to allow users to set the `deletionProtection` flag on the VM. As it turns out from digging into the compute API docs, this flag is not set by the `/instances/{id}/update` endpoint but instead by the `/instances/{id}/setDeletionProtection` endpoint.

Attempting to use `vm.update()` to set the deletionProtection flag results in a 5xx error:
```javascript
{
      code: 'INTERNAL_ERROR',
      message: "Internal error. Please try again or contact Google Support. (Code: '-2609096419922764667')"
    }
```

Based on the code that @stephenplusplus wrote to implement `vm.update()`, I was able to cobble this together, which works a treat:

```javascript
const metadata = {
      deletionProtection: false,
    };

    vm.getMetadata((err, currentMetadata) => {
      if (err) {
        throw(err);
        return;
      }

      vm.request(
        {
          method: 'POST',
          uri: 'setDeletionProtection',
          json: extend(true, currentMetadata, metadata),
        },
        async (err, op) => {
          await op.promise();
          });

          return res.status(200).send(op);
        }
      );
    });
```

All that to say, it looks like deletion protection will require its own method in the client library to mirror the behavior of the underlying REST api.

#### Environment details

  - OS: Mac OSX
  - Node.js version: v14.7.0
  - npm version: 6.14.7
  - `@google-cloud/compute` version: 2.1.0

#### Steps to reproduce

  1. Follow the example provided in the docs for `vm.update()`

**Comment by memyselfandm** [comment]
Some notes on my cobbled-together function:
1. since this no longer has anything to do with the vm's metadata, the wrapping `vm.getMetadata()` call can probably be eliminated for the actual implementation
2. the method has to be "POST" or the endpoint will 404
3. the way I'm passing the `deletionProtection` flag in seems to work, but because the API docs say its supposed to be a query parameter, I don't know if its the "right" way to do it.

**Comment by stephenplusplus** [comment]
Thanks for looking into this. Interestingly, I was able to successfully update the `deletionProtection` flag using the `update()` method while testing that PR. Could you share your code that didn't work?

**Comment by memyselfandm** [comment]
something along these lines. pretty close to the example you made for the documentation

```javascript
const metadata = {
      deletionProtection: false,
    };

    const [upOp] = await vm.update(metadata);
    await upOp.promise();
    console.log(mdOp);
```

**Comment by stephenplusplus** [comment]
Hmm, that's pretty close to what is working for me locally and our system tests:

```js
const assert = require('assert');

const [op1] = await vm.update({deletionProtection: false});
await op1.promise();
const [metadataBefore] = await vm.getMetadata();
assert.strictEqual(metadataBefore.deletionProtection, false);

const [op2] = await vm.update({deletionProtection: true});
await op2.promise();
const [metadataAfter] = await vm.getMetadata();
assert.strictEqual(metadataAfter.deletionProtection, true);
```

I think that error code you're getting, `-2609096419922764667`, needs to be investigated to determine its meaning. I don't believe the method is actually misbehaving. The message suggests reaching out to Google Support (https://cloud.google.com/compute/docs/getting-support). If you do, feel free to share the response. And definitely let us know if it is, indeed, a problem here.

Regarding adding support for "setDeletionProtection()", we could do that, although in general this library is missing many similar features and endpoints. A PR would be welcome to add that in, but I don't necessarily think we need it, as "update()" has it covered.
