### ISSUE TITLE
Adding support for VM suspend request

### ISSUE THREAD

**Issue by anaselfathi** [googleapis/nodejs-compute#489]
Hello,

I am trying to schedule an automatic VM suspension. I have been following this tutorial [https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule#console](https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule#console
)

I am wondering if adding this feature is as easy as duplicating the "stop" code. I made a pull request with this change.

**Comment by philipwigg** [comment]
I think we can close this now since we're not proceeding with the PR?

**Comment by bcoe** [comment]
@anaselfathi are you okay with my closing?

**Comment by anaselfathi** [comment]
Yes please close this issue. Thank you.
