### ISSUE TITLE
Generated doc pages are missing nested config items

### ISSUE THREAD

**Issue by zbjornson** [googleapis/nodejs-compute#50]
This is probably a more general issue than just googleapis/nodejs-compute, but if you look at e.g. the generated doc page for `zone.createVM` https://cloud.google.com/nodejs/docs/reference/compute/0.9.x/Zone#createVM
there are only three parameters: `name`, `config` and `callback` -- the `config.*` sub-parameters `os`, `http`, `https` and others are missing:

https://github.com/googleapis/nodejs-compute/blob/df05066130b7e1e423c5fcbd627d798f998846da/src/zone.js#L520-L537

**Comment by stephenplusplus** [comment]
Thanks for reporting. We have an issue for this at https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783.
