### ISSUE TITLE
backendBuckets support

### ISSUE THREAD

**Issue by mikeshultz** [googleapis/nodejs-compute#506]
If I missed this, let me know.  I've tried using `service.create()` with the backendBuckets configuration object but it appears `healthChecks` is required, which isn't part of the definition.

 **Is your feature request related to a problem? Please describe.**

I would like to be able to create a balancer with a GCS bucket backend.

 **Describe the solution you'd like**

Adding support for the [backendBuckets API](https://cloud.google.com/compute/docs/reference/rest/v1/backendBuckets)

 **Describe alternatives you've considered**

I'm currently looking for a lower level library to make the REST requests now while handling OAUTH.  Open to any pointers to the right place.

**Comment by mikeshultz** [comment]
So, to deploy a GCS bucket-backed Cloud CDN, it would need all of these API endpoints:

- `backendBuckets`
- `urlMaps`
- `globalAddresses`
- `globalForwardingRules`
- `targetHttpProxies`
- `targetHttpsProxies`
- `sslCertificates`

I ended up implementing this with [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs), so this isn't urgent for me but I bet these would be useful for this library.

**Comment by sofisl** [comment]
Hi @mikeshultz, please refer to the completely refactored version of this library, v3.1.0. Thank you!
