### ISSUE TITLE
create multiple of the same instances

### ISSUE THREAD

**Issue by luukk** [googleapis/nodejs-compute#521]
I'm trying to create multiple of the same instace using the compute nodejs sdk. Yet i couldn't find the correct field to this this in the documentation. How can i do this?

**Comment by stephenplusplus** [comment]
Are you looking for something like this?:

```js
const Compute = require('@google-cloud/compute').Compute;

const computeInstance1 = new Compute();
const computeInstance2 = new Compute();
```

**Comment by luukk** [comment]
No not really, I know that with Terraform you can use `count` which let you create multiple of the same instances. Is there some sort of keyword i can add to the object directly?

**Comment by alexander-fenster** [comment]
Please upgrade to the latest version of `@google-cloud/compute` which is a complete rewrite of the library. I'll close this issue for now.
