### ISSUE TITLE
Create VM from instance template without default machineType and networkInterfaces

### ISSUE THREAD

**Issue by dfeehrer** [googleapis/nodejs-compute#529]
**Current behavior**

The ability to create a VM from an instance template using `zone.createVM()` was implemented in #500. 

However, because `createVM()` sets defaults for `machineType` and `networkInterfaces` [here](https://github.com/googleapis/nodejs-compute/blob/master/src/zone.js#L585), creating a VM from an instance template results in the (in my opinion) unexpected behavior of the default `machineType` and `networkInterfaces` overriding whatever is defined in the instance template.

Ex:
Given example instance template: `example-instance-template`, machine type `n2d-standard-8` and a network interface with a PREMIUM network tier, the follow code:

```
const [vm, operation] = await zone.createVM(instanceName {
    template:
      "https://compute.googleapis.com/compute/v1/projects/project-name/global/instanceTemplates/example-instance-template",
  });
```
...results in a new VM being created with all the settings of `example-instance-template` except the machine type has been set to `n1-standard-1` and `networkInterfaces` is `[ { network: 'global/networks/default' } ]`.

A work around is just to explicitly specify the `machineType` and `networkInterfaces` explicitly when creating a VM:
```
const [vm, operation] = await zone.createVM(instanceName {
    template:
      "https://compute.googleapis.com/compute/v1/projects/project-name/global/instanceTemplates/example-instance-template",
    machineType: "n2d-standard-8",
    networkInterfaces: [
      {
        name: "nic0",
        network: "projects/project-name/global/networks/default",
        accessConfigs: [
          {
            name: "External NAT",
            type: "ONE_TO_ONE_NAT",
            kind: "compute#accessConfig",
            networkTier: "PREMIUM",
          },
        ],
        kind: "compute#networkInterface",
      },
    ],
  });
```

...but this sort of defeats the purpose and convenience of using an instance template, since now I have to set these parameters in my instance template and then specify them again when using the Node API to get everything to work as expected. And if it change the settings of the instance template, I now have to update my Node code as well if I want to keep them in sync.

 **Expected behavior**
If an instance template is passed in, the default `machineType` and `networkInterfaces` should not be set.
I think this would make this easier to use, but would love to hear about other opinions or if there's something I've overlooked.

Thanks!

**Comment by sofisl** [comment]
@stephenplusplus, I'm going to label this as a bug for now but I'm not clear on what the expected behavior is. Would you mind offering your thoughts? Thanks!

**Comment by stephenplusplus** [comment]
@dfeehrer thank you for pointing this out. I think your solution is correct. I'll get a PR set up and then tag you for thoughts, if you don't mind!
