### ISSUE TITLE
How to forceAttach a regional disk?

### ISSUE THREAD

**Issue by bharat42** [googleapis/nodejs-compute#531]
Not sure how to pass forceAttach param.
https://googleapis.dev/nodejs/compute/latest/VM.html#attachDisk

https://cloud.google.com/compute/docs/reference/rest/v1/instances/attachDisk

**Comment by stephenplusplus** [comment]
Looks like we don't have a way to get that setting through for now. Thank you for letting us know.

**Comment by sofisl** [comment]
Hello! We are migrating this repo over to google-cloud-node. If this is still a concern for you, we ask you kindly reopen the issue there. Thank you very much!
