### ISSUE TITLE
Image.create options are not passed correctly to Compute.createImage

### ISSUE THREAD

**Issue by cschuff** [googleapis/nodejs-compute#540]
When calling [Image.create](https://googleapis.dev/nodejs/compute/latest/Image.html#create) with parameters `disk` and `options` as described the call ends up in the following error:
```
TypeError: callback is not a function
      at onCreate (.../node_modules/@google-cloud/common/build/src/service-object.js:110:13)
```
This happens due to the wrong translation of parameters happening in `@google-cloud/common/build/src/service-object.js` between
* [Image.create(disk, options)](https://googleapis.dev/nodejs/compute/latest/Image.html#create)
* [Compute.createImage(name, disk, options, callback)](https://googleapis.dev/nodejs/compute/latest/Compute.html#createImage)

The proxy method is not capable of handling any additional parameters...

Parameters end up like follows:
Compute.createImage(
  ✅ name = imageName, 
  ✅ disk = imageCreate.disk, 
  ⚠️ options = imageCreate.options wrapped as a callback ⚠️, 
  callback = undefined
)

1) Is this a client library issue or a product issue?
This is the client library for nodejs.

2) Did someone already solve this?
No

3) Do you have a support contract?
Yes, ticket created referencing this github issue

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: OS X 11.1
  - Node.js version: 12.19.0
  - npm version: 6.14.8
  - `@google-cloud/compute` version: 2.4.2

#### Steps to reproduce

  1. create a VM
  2. create an image using [Image.create](https://googleapis.dev/nodejs/compute/latest/Image.html#create) like follows:
```
const compute = new Compute({ projectId, keyFilename: this.secretKeyFile });
const disk = compute.zone('europe-west5-a').disk('diskName');
// this line fails with `TypeError: callback is not a function`
const [, operation] = await compute.image('imageName').create(disk, { labels: { foo: 'bar' } });
await new Promise((resolve, reject) => {
    operation.on('complete', (data: any) => resolve(data));
    operation.on('error', (err) => reject(err));
  });
console.log('image successfully captured');
```

Thanks!

**Comment by cschuff** [comment]
Furthermore the docs [Compute.createImage](https://googleapis.dev/nodejs/compute/latest/Compute.html#createImage) falsely claims that the returned Promise resolves to
```
compute.createImage('new-image', disk).then(function(data) {
  var operation = data[0];
  var apiResponse = data[1];
});
```
while it actually resolves to
```
compute.createImage('new-image', disk).then(function(data) {
  var image = data[0];
  var operation = data[1];
  var apiResponse = data[2];
});
```

**Comment by stephenplusplus** [comment]
Thanks for reporting! I'll look into this and let you know when I have a PR.

**Comment by stephenplusplus** [comment]
PR sent! #541. Please take a look!

**Comment by cschuff** [comment]
LGTM

thx!
