### ISSUE TITLE
support targetProxy, sslCertificate, and urlMaps configuration

### ISSUE THREAD

**Issue by ggprod** [googleapis/nodejs-compute#550]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

It would be nice to be able to create or update all load balancer components with this library.  It currently supports forwarding rules and backend services but not target proxies, ssl certificates or url maps.

**Comment by sofisl** [comment]
Hello! We are migrating this repo over to google-cloud-node. If this is still a concern for you, we ask you kindly reopen the issue there. Thank you very much!
