### ISSUE TITLE
Support for regionDisks

### ISSUE THREAD

**Issue by aslafy-z** [googleapis/nodejs-compute#582]
The API lets us retrieve all the disks but can only delete zonal disks and not regional.

**Comment by vchudnov-g** [comment]
This is an API design issue for the Compute Engine team to process.

**Comment by SurferJeffAtGoogle** [comment]
Thank you for requesting this issue.  I agree the API would benefit from this improvement.

Please open an issue here:
https://issuetracker.google.com/issues/new?component=187134&template=0

The people who build the API don't look for issues here.
