### ISSUE TITLE
Merge "diregapic" branch into master branch

### ISSUE THREAD

**Issue by summer-ji-eng** [googleapis/nodejs-compute#584]
cc: @alexander-fenster @bcoe @danoscarmike 

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by bcoe** [comment]
@summer-ji-eng this sounds good 👍 even if we land work to the main branch, and don't launch immediately, I'd rather push us towards getting this out the door.

I think our users will love this.

**Comment by vchudnov-g** [comment]
Is there a plan for or update on this? (Feel free to respond internally if appropriate)

**Comment by vchudnov-g** [comment]
ping @summer-ji-eng

**Comment by vchudnov-g** [comment]
Gentle ping @summer-ji-eng 
@xmasreturns needs to know when this happens...

**Comment by summer-ji-eng** [comment]
The merge should be around Aug second week.

**Comment by vchudnov-g** [comment]
Is this done? Please confirm so @Xmasreturns can update doc links.

**Comment by alexander-fenster** [comment]
It is done.
