### ISSUE TITLE
Retry option for lower level Errors (e.g. ECONNRESET or ETIMEDOUT)

### ISSUE THREAD

**Issue by jacklty** [googleapis/nodejs-compute#65]
Hello, could we have the option to retry any lower level errors (e.g. socket hang up, DNS resolution error, etc)? I saw the enhancement in retry-request for that purpose (https://github.com/stephenplusplus/retry-request/commit/e25c836835490d7c8187482aa7715ffeaf35d198), but there is no easy way to config it through ClientConfig in `@google-cloud/compute`

Thanks

#### Environment details

  - Node.js version: 4.2.3
  - npm version: 3.5.2
  - `@google-cloud/compute` version: 0.8.0

**Comment by stephenplusplus** [comment]
Thanks for the suggestion! Is this something you'd want to use client-wide, for all methods? Or is there a particular method that would benefit?

**Comment by jacklty** [comment]
I personally think client-wide will serve us well because that type of errors are not likely to be specific to any cloud API calls. Thanks

**Comment by sofisl** [comment]
Hi, please refer to the new library, ^3.0.0.
