### ISSUE TITLE
Default `projectId` passed to client is not used by client functions

### ISSUE THREAD

**Issue by mscdex** [googleapis/nodejs-compute#676]
#### Environment details

  - OS: n/a
  - Node.js version: v16.13.2
  - npm version: n/a
  - `@google-cloud/compute` version: 3.1.0

[`projectId` passed to a client constructor](https://github.com/googleapis/gax-nodejs/blob/80f7139556dcccbdd3559414d0bd59c4934e6491/client-libraries.md#authentication-options) is not used as a default for functions that require a project id (e.g. `aggregatedListAsync()`). This also means that the `GCLOUD_PROJECT` environment variable is ignored.

**Comment by sofisl** [comment]
@mscdex, can you provide the code sample along with the output that determines which project you're using, and can you confirm that you are not logged in with your default application credentials by using [gcloud auth application-default revoke](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/revoke)? 

As a note, here are the [many ways you can authenticate](https://cloud.google.com/docs/authentication/production), and sometimes these can stomp on each other.

**Comment by mscdex** [comment]
@sofisl There is no code example really, the issue speaks for itself.

This project/repo depends on `google-gax` which is used in communicating with the Google Cloud APIs. As I initially linked, it is documented as having a `projectId` auth option:

> * options.projectId: the project ID from the Google Developer's Console, e.g. `grape-spaceship-123`. We will also check the environment variable `GCLOUD_PROJECT` for your project ID.

This and other options are also re-documented in the code for the various client classes in this project. For example [`InstancesClient` shows](https://github.com/googleapis/nodejs-compute/blob/11713af4b429bf2111ef9a2961f6389dca38a777/src/v1/instances_client.ts#L68-L101) that it supports `projectId` and other useful config options, yet when you create a new `InstancesClient` and pass `projectId` to it and try to make some client requests, they fail because of a missing `projectId`.

I haven't tried recently to see if things have changed, but by the looks and sounds of it, it's still a problem.

**Comment by sofisl** [comment]
Ah, thanks for the clarification @mscdex. I think the confusion lies that those configuration options are for [authentication](https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#authentication-options) specifically, not for setting configuration options for the resulting methods (i.e., you still need to pass the projectId specifically for some methods). Hope this helps!

**Comment by mscdex** [comment]
@sofisl I'm not able to reopen this, but if that's the case can we turn this into a feature request? Otherwise I can open a new issue for that. The feature request would be two parts:

1. Make `projectId` passed to a client constructor be the default for that client's requests
2. If 1 isn't acceptable for some reason, have the documentation clearly state that `projectId` is only used for authentication and not for client request defaults.
