### ISSUE TITLE
Copy-paste error in createInstanceFromCustomImage.js sample

### ISSUE THREAD

**Issue by mscdex** [googleapis/nodejs-compute#677]
#### Environment details

  - OS: n/a
  - Node.js version: n/a
  - npm version: n/a
  - `@google-cloud/compute` version: main branch

The function here:

https://github.com/googleapis/nodejs-compute/blob/1301ff9aab2baf75f4595a0e34504b367a172cce/samples/instances/create-start-instance/createInstanceFromCustomImage.js#L37

should be named `createInstanceFromCustomImage` instead.

**Comment by FrodoTheTrue** [comment]
PR is here: https://github.com/googleapis/nodejs-compute/pull/69
