### ISSUE TITLE
VMDisk Snapshot

### ISSUE THREAD

**Issue by amritkandel** [googleapis/nodejs-compute#701]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I need to take manual backups on GCP and looking for ways to automate it 
 **Describe the solution you'd like**
Create VM Disk backups using nodejs.
 **Describe alternatives you've considered**
 **Additional context**
https://github.com/andrikosrikos/Google-Cloud-Functions/blob/master/Node.js/backupVMDiskSnapshot.js

**Comment by sofisl** [comment]
Hello! We are migrating this repo over to google-cloud-node. If this is still a concern for you, we ask you kindly reopen the issue there. Thank you very much!
