### ISSUE TITLE
ForwardingRulesClient.delete() is not deleting the load balancers

### ISSUE THREAD

**Issue by sergeymirzoyan1991** [googleapis/nodejs-compute#707]
#### Environment details

  - `OS`: N/A
  - `Node.js version`: 16.4.1
  - `npm version`: 7.19.1
  - `@google-cloud/compute`: 3.1.2:

#### Steps to reproduce

  1. Create a load balancer
  2. Use `@google-cloud/compute` to remove the load balancer
  3. Go to the console(UI) and have a look at the load balancers

After calling `(new ForwardingRulesClient()).delete({forwardingRule, region, project})` to delete a load balancer, a success response is returned, which means that the load balancer should have been deleted.
But the load balancer is still visible in the console(UI), and there is a note on the load balancer: `This load balancer has TCP/UDP mixed configuration. Use gcloud or REST API to delete it.`
And after calling `gcloud` command to delete it, a failure is returned: `ERROR: (gcloud.compute.forwarding-rules.delete) Could not fetch resource:`

Thanks!

**Comment by alexander-fenster** [comment]
`ForwardingRulesClient.delete()` is a long running method; it starts a background long running operation (that could be successful or could fail) and it cannot immediately return success or failure. We will update the library soon (within weeks) to support the long running operations, after which, `const [operation] = await client.delete(...); const [response] = await operation.promise()` will throw an error if the operation has failed.

I'll close this issue for now, you can follow the long running operation support progress in https://github.com/googleapis/gapic-generator-typescript/pull/1150.
