### ISSUE TITLE
README: Samples section should mention auto-generated samples

### ISSUE THREAD

**Issue by arekkusu** [googleapis/nodejs-compute#757]
### Summary

I realized there are a number of auto-generated samples in the [`samples/generated`](https://github.com/googleapis/nodejs-compute/tree/main/samples/generated/) which are are helpful but not clearly mentioned in the README and therefore easy to miss.

### Expectation

* Add a mention about the autogenerate sample in the [README](https://github.com/googleapis/nodejs-compute/blob/main/README.md)
  * If preferred more detailed could be included

**Comment by sofisl** [comment]
Closing in lieu of: https://github.com/googleapis/synthtool/issues/1495
