### ISSUE TITLE
List of all Regions and Zones

### ISSUE THREAD

**Issue by sniffski** [googleapis/nodejs-compute#764]
Dear team,
I'm trying to choose proper region for my instance following "some" criteria I have, but can't seem to find a way to list all available regions and zones... Especially I need the country or city information about each region as it is in the web interface.
Any samples how to complete that will be much appreciated! 
Thanks

**Comment by sofisl** [comment]
Hi @sniffski, hope [this](https://cloud.google.com/compute/docs/regions-zones) helps - feel free to reopen if not.

**Comment by sniffski** [comment]
> Hi @sniffski, hope [this](https://cloud.google.com/compute/docs/regions-zones) helps - feel free to reopen if not. 

In fact that's exactly what I'm using, but currently parsing the table in a JSON and then using that JSON for further processing... I was hoping there is an API call I can use that will give me the same filtering experience as per this page...
