### ISSUE TITLE
Feature Request: use client constructors' `options.projectId` as default project ID for client methods

### ISSUE THREAD

**Issue by mscdex** [googleapis/nodejs-compute#790]
**Is your feature request related to a problem? Please describe.**
It's annoying to have to pass `projectId` to every client method if the project ID never changes for the particular client instance.

 **Describe the solution you'd like**
Have client methods default to `options.projectId` passed to the client constructor when an explicit `project` is not passed to client methods.

 **Describe alternatives you've considered**
Flipping a table.

**Comment by sofisl** [comment]
Hello! We are migrating this repo over to google-cloud-node. If this is still a concern for you, we ask you kindly reopen the issue there. Thank you very much!
