### ISSUE TITLE
sample test 'should create vm' fails in nightly

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-compute#82]
This looks like a new (and flaky) failure of the new test that was recently added in #80. Could you please take a look at the failure?

https://circleci.com/gh/googleapis/nodejs-compute/1967

Thanks!

**Comment by fhinkel** [comment]
I can't reproduce it and it didn't flake again. Closing this but I'll keep an eye out for more failures.

**Comment by alexander-fenster** [comment]
Here we go again :( https://circleci.com/gh/googleapis/nodejs-compute/2040
This time it just timed out I guess.

**Comment by fhinkel** [comment]
Sorry, the integration test I added is not robust. 

Here's a fix for the "could not find resource" problem: https://github.com/googleapis/nodejs-compute/pull/85

I'll go ahead and increase the timeout? 200 seconds seems long, but I guess not long enough.
