### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by VincentJ711** [googleapis/nodejs-compute#83]
I'd like to write about my thoughts on using parts of this library. Is there a proper place to do so?

**Comment by stephenplusplus** [comment]
Individual issues for bugs and feature requests would suit our discussion -> completion workflow format. If it's more of an abstract collection of thoughts, then I suppose this issue is a fine place, and we can disseminate as necessary.

Thanks in advance!

**Comment by VincentJ711** [comment]
Ok I finally figured out how to do what I needed to. I suppose this can be closed. But to make it somewhat helpful for the next person, I would recommend making the documentation it a bit more clear on where to find the config options object when using VM.prototype.create. I would suggest making a direct link from [the config parameter](https://cloud.google.com/nodejs/docs/reference/compute/0.10.x/VM#create) to the [instance resource](https://cloud.google.com/compute/docs/reference/rest/v1/instances). What also helped me tremendously was filling out a vm template using the cloud console and then looking at the "Equivalent REST" to see all the instance resource options I would need to use in VM.prototype.create. Perhaps reference this wonderful tool in your README. 
<br>
<img width="222" alt="screen shot 2018-05-12 at 7 15 16 pm" src="https://user-images.githubusercontent.com/25497140/39963191-bcf52c2c-5619-11e8-9c3e-5bd4f5e3651d.png">


With that said I'm looking at a lot of config options that I'm not sure I should fill out.
```
const INSTANCE_NAME = 'instance-1';
const INSTANCE_REGION = 'us-west1';
const INSTANCE_ZONE = 'us-west1-a';
const compute = new Compute();
const zone = compute.zone(INSTANCE_ZONE);
const vm = zone.vm(INSTANCE_NAME);

const config = {
  name: INSTANCE_NAME,
  zone: INSTANCE_ZONE,
  networkInterfaces: [
    {
      subnetwork: 'regions/{INSTANCE_REGION}/subnetworks/default'
      ...
    }
  ],
  disks: [
    {
      deviceName: INSTANCE_NAME,
      initializeParams: {
        diskType: 'zones/{INSTANCE_ZONE}/diskTypes/pd-ssd'
        ...
      }
    }
  ]
  ...
}

vm.create(config).then.....
```
For example, look at all the duplicated names/regions/zones.
It's unclear what the module will automatically fill out. To be safe I'll be redundant and replace everything myself. Overall though, great module.

**Comment by fhinkel** [comment]
@VincentJ711 Thanks for the feedback! We can definitely improve the docs for the config object. It's very confusing what the default values are and what needs to be specified. Thanks! I'll try to send a PR next week and would very much appreciate your input on it! 🙏

**Comment by meredithslota** [comment]
Hi there! I'm going to close this out, but if you have new issues, please file them! We're always working on improving the documentation, and you might also want to check our our central Node.js client library references here: https://cloud.google.com/nodejs/docs/reference/compute/latest
